In [155]:
# Simple Employee Management System
#Allows us to keep track of everyone working and their information
import pandas as pd
from IPython.display import display
employees =[]

def load_employees():
  """Load employees from CSV"""
  global employees
  try:
    df=pd.read_csv("employees.csv")
    employees=df.to._dict(orient="records")
    print("Employees loaded from employees.csv\n")
  except FileNotFoundError:
    print("No employees.csv file found. Starting with an empty list.\n")

  load_employees()

In [156]:
def add_employee():
  """Adds a new employee with input validation and optional ID to the system"""
  while True:
    name=input("Enter employee name: ").strip()
    if name:
      break
    print("Name cannot be empty.")
  while True:
    department=input("Enter department: ").strip()
    if department:
      break
    print("Department cannot be empty.")
  while True:
    salary_input=input("Enter Salary: ").replace(",", "")
    if salary_input.replace(".","", 1).isdigit(): #allows decimals
      salary =float(salary_input)
      break
    else:
      print('Invalid Salary. Try Again.')
  employee_id=len(employees)+1
  employees.append({"id": employee_id, "name": name, "department": department, "salary": salary})
  print(f"{name} added successfully!\n")

In [157]:
def view_employees():
  """Displays all employees in a table sorted by salary"""
  if not employees:
    print("No employees found.\n")
    return
  df=pd.DataFrame(employees)
  df['salary']=df['salary'].apply(lambda x: f"${x:,.2f}")
  df=df.sort_values(by='salary', ascending=False)
  display(df)

In [158]:
def update_employee():
  """Update employee Information by ID"""
  if not employees:
    print("Not employees to update.\n")
  try:
    emp_id=int(input("Enter the employee ID to update: "))
  except ValueError:
      print("Invalid ID.\n")
      return

  for emp in employees:
    if emp["id"] == emp_id:
      new_department=input(f"Enter the new department (current:{emp['department']})").strip()
      new_salary_input=input(f"Enter the new salary (current: {emp['salary']})").replace(",", "")

      if new_department:
        emp['department']=new_department
      if new_salary_input:
        try:
          emp['salary']=float(new_salary_input)
        except ValueError:
            print("Invalid salary. Salary not changed.")

      print(f"Employee ID {emp_id} information updated successfully!\n")
      return
  print(f"No employee found with the ID {emp_id}\n")

In [159]:
def delete_employee():
    """Delete an employee by their ID from the system"""
    if not employees:
      print("No employees to delete.\n")
      return
    try:
      emp_id=int(input("Enter the employee ID to delete:"))
    except ValueError:
      print("Invalid ID.\n")
      return

    for emp in employees:
        if emp["id"] ==emp_id:
           employees.remove(emp)
           print(f"Employee ID {emp_id} removed successfully!\n")
           return
    print(f"No employee found with the ID {emp_id}\n")

In [160]:
def view_stats():
  """Displays basic stattics about employees"""
  if not employees:
    print("No employees to calculate statistics for.\n")
    return
  total=len(employees)
  average_salary = sum(emp['salary'] for emp in employees) / total
  print(f"Total employees: {total}")
  print(f"Average salary: ${average_salary:,.2f}\n")

  #Department Summary
  df=pd.DataFrame(employees)
  summary=df['department'].value_counts()
  print("Employees per department:\n")
  print(summary.to_string())

In [161]:
def save_employees():
  """Save employees to CSV"""
  df=pd.DataFrame(employees)
  df.to_csv("employees.csv", index=False)
  print("Employees saved to employees.csv\n")

In [162]:
def main():
  """Main Menu to interact with the system"""
  while True:
    print("===Employee Management System===")
    print("1: Add Employee")
    print("2: View Employees")
    print("3: Update Employee")
    print("4: Delete Employee")
    print("5: View Statistics")
    print("6: Save Employees")
    print("7: Exit")
    choice=input('Choose an option:')

    if choice=='1':
      add_employee()
    elif choice=='2':
      view_employees()
    elif choice=='3':
      update_employee()
    elif choice=='4':
      delete_employee()
    elif choice=='5':
      view_stats()
    elif choice=='6':
      save_employees()
    elif choice=='7':
      print("Exiting the system. Goodbye!")
      save_employees()
      break
    else:
      print("Invalid choice. Please try again.\n")

main()

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:1
Enter employee name: Ahmad Elsaad
Enter department: IT
Enter Salary: 100,000
Ahmad Elsaad added successfully!

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:1
Enter employee name: Alexis Smith
Enter department: HR
Enter Salary: 86,000
Alexis Smith added successfully!

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:1
Enter employee name: Zach Jones
Enter department: Operations
Enter Salary: 120,000
Zach Jones added successfully!

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:1
Enter employee name: John Joe
Enter department: Finance
Enter Salary: 110,000
John Joe added successfully!

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:1
Enter employee name: April Snow
Enter department: Marketing
Enter Salary: 80,000
April Snow added successfully!

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:1
Enter employee name: Caroline Hunter
Enter department: Sales
Enter Salary: 60,000
Caroline Hunter added successfully!

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:6
Employees saved to employees.csv

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:2

   id             name  department       salary
1   2     Alexis Smith          HR   $86,000.00
4   5       April Snow   Marketing   $80,000.00
5   6  Caroline Hunter       Sales   $60,000.00
2   3       Zach Jones  Operations  $120,000.00
3   4         John Joe     Finance  $110,000.00
0   1     Ahmad Elsaad          IT  $100,000.00

===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:5
Total employees: 6
Average salary: $92,666.67

Employees per department:

department
IT            1
HR            1
Operations    1
Finance       1
Marketing     1
Sales         1
===Employee Management System===
1: Add Employee
2: View Employees
3: Update Employee
4: Delete Employee
5: View Statistics
6: Save Employees
7: Exit
Choose an option:7
Exiting the system. Goodbye!
Employees saved to employees.csv